.github/workflows


pacman.yml


README.md


name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}


      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Level Up Your README
Anyone can use templates — but when you know what you’re doing, it shows.

👉 Explore resources that will upgrade your skills — and your README. Start now.


Clean Code
A Handbook of Agile Software Craftsmanship by Uncle Bob.

Get the book

Clean Architecture
Software Architecture Solutions from Uncle Bob.

Get the book

Explore More Books
Browse the full list of curated titles to boost your coding skills.

More books
💡 This panel contains affiliate links. If you find something useful and make a purchase, I may earn a small commission ☕. Thanks for the support ❤
Profile Readme Generator
